version: '3.8'

services:
  yogsstats:
    build:
      context: .
      args:
        POSTGRES_PASSWORD: zacharias00
        POST_PASSWORD: $$2a$10$$WVgswKX5Lhc/8arsPwesmeDpqZY0KSGPCL5OLrSolAB.ZWhU4smje
        HOST_IP: 10.0.2.15
    network_mode: "host"
    restart: always
    ports:
      - 80:80