version: '3.8'

services:
  yogsstats:
    build:
      context: backend/
      args:
        POSTGRES_PASSWORD: pass
        POST_PASSWORD: pass
        HOST_IP: ip
    network_mode: "host"
    restart: always
    ports:
      - 5001:5001
  
  yogsstats-frontend:
    build: 
      context: frontend/
    network_mode: "host"
    restart: always
    ports:
      - 5002:5002