version: '3.8'

services:
  yogsstats:
    build:
      context: .
      args:
        POSTGRES_PASSWORD: ${PQL_PASS}
        POST_PASSWORD: $$2a$10$$WVgswKX5Lhc/8arsPwesmeDpqZY0KSGPCL5OLrSolAB.ZWhU4smje
        HOST_IP: 127.0.0.1
    network_mode: "host"
    restart: always
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt/:rw"

  yogsstats-frontend:
    build: 
      context: ../yogsstats-frontend
    ports:
      - 3000:443
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt/:rw"