version: '3.8'

services:
  yogsstats:
    build:
      context: .
      args:
        POSTGRES_PASSWORD: pass
        POST_PASSWORD: pass
        HOST_IP: 10.0.2.15
    network_mode: "host"
    restart: always
    ports:
      - 80:80