alter table team add colour text;
update team set colour = 'green' where team = 'innocents';
update team set colour = 'red' where team = 'traitors';
update team set colour = 'black' where team = 'zombies';
update team set colour = 'yellow' where team = 'bees';
update team set colour = 'purple' where team = 'jester';
update team set colour = 'pink' where team = 'clown';
update team set colour = 'brown' where team = 'elves';
update team set colour = '#8b0000' where team = 'communists';
update team set colour = '#FF69B4' where team = 'lovers';
update team set colour = '' where temm = 'none';